### ISSUE TITLE
Text Generation With Pytorch in a RuntimeError

### ISSUE THREAD

**Issue by LeremyLin** [ChunML/NLP#3]
Hi there, 
   I have followed the code in your text generation with pytorch 1.1.0 under the win10, but get some error message.

      ''RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAType instead (while checking arguments for embedding)''

Do you have any suggestions for that?
Thank you!

**Comment by ChunML** [comment]
Hi there,

Can you provide mode details on that? Or just paste the console log on here and I'll take a look.

**Comment by LeremyLin** [comment]
Hi there, 

I think I have figured it out. I just modified the input training data x from 'x = torch.tensor(x).to(device)' to 'x = torch.tensor(x).to(device).long()'.

And for the prediction part, I also modify 'ix = torch.tensor([[vocab_to_int[w]]]).to(device)' to 'ix = torch.tensor([[vocab_to_int[w]]]).to(device).long()'

It's just about transforming the data into the long type.

**Comment by ChunML** [comment]
Hi,

Hope to hear that you solved the problem :) I haven't come across that before. I'll try with the latest version of Pytorch when I have time.
